/* automatically generated by rust-bindgen */

pub type my_bool = ::std::os::raw::c_char;
pub const Item_result_STRING_RESULT: Item_result = 0;
pub const Item_result_REAL_RESULT: Item_result = 1;
pub const Item_result_INT_RESULT: Item_result = 2;
pub const Item_result_DECIMAL_RESULT: Item_result = 4;
pub type Item_result = u32;
pub const MYSQL_ERRMSG_SIZE: ::std::os::raw::c_uint = 512;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_udf_args {
    pub arg_count: ::std::os::raw::c_uint,
    pub arg_type: *mut Item_result,
    pub args: *mut *mut ::std::os::raw::c_char,
    pub lengths: *mut ::std::os::raw::c_ulong,
    pub maybe_null: *mut ::std::os::raw::c_char,
}
pub type UDF_ARGS = st_udf_args;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_udf_init {
    pub maybe_null: my_bool,
    pub decimals: ::std::os::raw::c_uint,
    pub max_length: ::std::os::raw::c_uint,
    pub ptr: *mut ::std::os::raw::c_char,
    pub const_item: my_bool,
}
pub type UDF_INIT = st_udf_init;
